version: '3'
services:
  blackcandy:
    image: ghcr.io/blackcandy-org/blackcandy:edge
    volumes:
      # - $PWD/production.sqlite3:/app/db/production.sqlite3
      - $PWD/uploads_data:/app/public/uploads
      - $PWD/../media-server/music:/media_data
    environment:
      - MEDIA_PATH=/media_data
    ports:
      - 6969:3000

