version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - $PWD/data:/config
      - $PWD/../media-server/movies:/movies #optional
      - $PWD/../media-server/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

