# Home Assistant
version: '3.5'
services:
  homeassistant:
    image: homeassistant/home-assistant
    container_name: homeassistant
    ports:
      - 8123:8123
    volumes:
      - $PWD/config:/config
      - $PWD/cache:/cache
      - $PWD/db:/db
    restart: 'unless-stopped'
    privileged: true
